server:
  port: 3000

spring:
  logging:
    level:
      org.springframework: DEBUG
  config:
    import:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ccdccd
    url: jdbc:mysql://localhost:3306/delivery?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    scan:
      packages: io.chechi.auto.entity
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
 # http:
  #  encoding:
  #    charset: UTF-8
  #    enabled: true
   #   force: true

image:
  upload:
    directory: D:\Spring Boot Projects\FoodDelivery\delivery\src\main\resources\images

